
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: nationalbank
    ports:
      - "3306:3306"
    networks:
      - nationalbank-network
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s

  backend:
    image: nationalbank-backend
    container_name: backend_container
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/nationalbank?useSSL=false&allowPublicKeyRetrieval=true&useTimezone=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - nationalbank-network

  test-runner:
    image: maven:3.8.8-eclipse-temurin-17
    container_name: test_runner
    depends_on:
      - mysql
      - backend
      - sonarqube
    networks:
      - nationalbank-network
    volumes:
      - .:/app
    working_dir: /app
    environment:
      SONAR_HOST_URL: "http://sonarqube:9000"
      SONAR_TOKEN: "squ_65db13a9b849a3ad6e22c24cd76ef02e0d806117"
    command: [ "mvn", "clean", "verify", "sonar:sonar" ]


  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube_container
    restart: always
    ports:
      - "9000:9000"
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    networks:
      - nationalbank-network
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

networks:
  nationalbank-network:
    driver: bridge
    external: true

volumes:
  mysql_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
