version: '3.8'

services:
  backend:
    image: nationalbank-backend
    container_name: backend_container
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/nationalbank?useSSL=false&allowPublicKeyRetrieval=true&useTimezone=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
